baseURL = "https://memo.touyu.me"
languageCode = "ja"
title = "memo.touyu.me"
theme = "m10c"
paginate = 15

[params]
  author = "touyu"
#   description = "This is just a memorandum."
  customCSS = ["/css/custom.css"]
  images = ["og.png"]

[params.style]
  # darkestColor = "#463625"
#   darkestColor = "#000000"
  darkColor = "#333333"
  primaryColor = "#3498db"
  lightColor = "#dddddd"
  # lightestColor = "#ffffff"
  