backend:
  name: github
  repo: touyu/memo
  branch: netlify-cms
media_folder: "static/images"
public_folder: "public"
publish_mode: editorial_workflow
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "date", required: false}
      - {label: "Eyecatch", name: "eyecatch", widget: "image", required: false}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Slug", name: "slug", widget: "string", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown", required: false}